name: Deploy
on: 
  workflow_dispatch:

jobs:  
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Container Registry
      uses: docker/login-action@v1 
      with:
        username: nologin
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
        registry: rg.fr-par.scw.cloud/achampion
    - name: Build Bargio
      run: |
        docker build . -t rg.fr-par.scw.cloud/achampion/bargio:latest
        docker push rg.fr-par.scw.cloud/achampion/bargio:latest
    - name: Update K8S resources
      uses: danielr1996/kubectl-action@1.0.0
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: |
          apply -f k8s.yaml          
    - name: Roll out old pods
      uses: danielr1996/kubectl-action@1.0.0
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        args: |
          rollout restart deploy bargio
          